const fs = require('fs');
const path = require('path');

const THEMES = {
  surcotes: {
    nom: "Les trucs surcotés",
    description: "Des choses que tout le monde adore, mais qui ne méritent pas tant de hype. Osez dire la vérité !",
    emoji: "💸",
    hardcore: false,
    consigne_haut: "Le plus surcoté",
    consigne_bas: "Le moins surcoté",
    mots: [
      "Les brunchs le dimanche",
      "Dubaï",
      "Les messages vocaux de plus d'une minute",
      "Les toasts à l'avocat",
      "La série La Casa de Papel",
      "Le Nouvel An",
      "Les sushis",
      "Les films Marvel",
      "Les Airpods",
      "Paris",
      "Les mariages",
      "L'été et la canicule",
      "Les festivals de musique",
      "Le Matcha",
      "La raclette (oui, on ose)",
      "Les friperies",
      "Netflix",
      "Les chats",
      "Les bières IPA",
      "Le camping",
      "Les influenceurs lifestyle",
      "Le télétravail",
      "Le café Starbucks",
      "Les burgers gourmets à 20 balles",
      "Les Escape Games",
      "Le champagne",
      "Les soirées déguisées",
      "La fête de la musique",
      "Le yoga",
      "Les baskets blanches",
      "Les huîtres",
      "Les rooftop",
      "Le Nutella",
      "Les jeux de société trop longs",
      "Les parcs d'attractions",
      "Les photos argentiques",
      "Le pain au chocolat",
      "Les musées d'art contemporain",
      "Les documentaires true-crime",
      "Les playlists Lo-Fi",
      "La salle de sport",
      "Les road trips",
      "Le ski",
      "Les trottinettes électriques",
      "Le vin nature",
      "Les macarons",
      "Le Black Friday",
      "Les podcasts de développement personnel",
      "Les cafés de spécialité",
      "Les poké bowls",
      "Le padel",
      "Les soirées karaoké",
      "Les festivals à 100 balles la journée",
      "Les baskets Samba d'Adidas",
      "L'iPhone qui sort chaque année",
      "Partir en vacances en groupe de 15",
      "Le bubble tea",
      "L'astrologie et les thèmes astraux",
      "Les stories privées Insta",
      "Faire la fête jusqu'à 7h du matin",
      "Les boîtes de nuit avec entrée payante",
      "Les soirées Halloween",
      "Les barbecues où les saucisses sont cramées",
      "Les photos BeReal prises 10h en retard",
      "Les restos 'Instagrammables' pas bons",
      "Le kombucha",
      "Les écouteurs sans fil qui tombent tout le temps",
      "Les comédies françaises récentes",
      "Les sneakers de collection",
      "Les influenceurs de Dubaï",
      "Les voyages organisés",
      "Le prosecco",
      "Les blind tests où personne ne connaît",
      "Les marques de luxe de seconde main",
      "Les cinémas chers à 16 euros",
      "Le concept de 'Morning Routine'",
      "Les podcasts de 2 heures",
      "Les déguisements de groupe",
      "Les verres d'eau à 4 euros en terrasse",
      "Les burgers sans pain",
      "Le pain au levain trop dur",
      "Les tatouages flash improvisés",
      "Les soirées d'intégration",
      "Les week-ends à Amsterdam",
      "Les terrasses chauffées l'hiver",
      "Les jus détox",
      "Les séries de 8 saisons",
      "Les afterworks obligatoires",
      "La bière sans alcool",
      "Les applications de rencontre",
      "Le paddle sur l'eau",
      "Les lunettes de soleil de créateur",
      "Les fêtes foraines",
      "Les gâteaux trompe-l'œil",
      "Les vlogs de vacances de 45 minutes",
      "La Saint-Valentin",
      "Les barbes de hipster taillées au millimètre",
      "Les vidéos d'unboxing sur YouTube",
      "Les soldes d'hiver",
      "Les hôtels 5 étoiles hors de prix",
      "Les bougies parfumées à 40 euros"
    ]
  },
  apero: {
    nom: "Apéro et Soirée arrosée",
    description: "Alcools traîtres, mélanges interdits, shots de la mort et délires de fins de soirée.",
    emoji: "🍻",
    hardcore: false,
    consigne_haut: "Plus jamais je bois",
    consigne_bas: "J'adore ça",
    mots: [
      "La Villageoise (vin en brique)",
      "Le shot de Tequila sans sel ni citron",
      "Le mélange bière + vodka (la sous-marinade)",
      "La Maximator (bière à 11%)",
      "Le Ricard chaud sans glaçon",
      "Le Jägerbomb à 3h du matin",
      "Finir les fonds de verres de la veille",
      "Le shot de tabasco ou piment en gage",
      "La vodka premier prix de supermarché",
      "Le cidre chaud éventé",
      "Le Get 27 tiède",
      "La Suze",
      "Le cubi de rosé tiède au soleil",
      "Le pastis à 10h du matin",
      "Le shot de chartreuse à 55 degrés",
      "Le gin pur sans tonic",
      "Le vin rouge avec un goût de vinaigre",
      "Le shot poubelle (mélange de tous les fonds de verres)",
      "Boire au goulot d'une bouteille chaude",
      "La Leffe rubis tiède",
      "Le rhum ambré pur sans glace",
      "Le shot cul-sec de tequila frappée",
      "Le trou normand improvisé",
      "La sangria maison avec des fruits douteux",
      "La bière sans alcool",
      "Le fond de canette avec de la cendre dedans",
      "La bière 8.6 chaude dans le métro",
      "Le cocktail bleu fluorescent qui tache les dents",
      "Le mélange whisky - jus d'orange premier prix",
      "Le shooter enflammé où tu te brûles les lèvres",
      "La vodka caramel écœurante",
      "Le vin mousseux à 2 euros qui donne la migraine",
      "L'alcool de prune de grand-mère oublié au grenier",
      "La bière IPA trop amère au goût de sapin",
      "Le shooter de liqueur de menthe verte",
      "Boire dans un verre en plastique cassé",
      "L'alcool à 90 degrés ramené de Pologne",
      "Le punch où on ne sent pas l'alcool mais qui t'assomme",
      "La Desperados sans bulles",
      "Le Spritz sans bulles et trop amer",
      "Le cul-sec imposé par les potes en criant",
      "La bouteille de gin tiède cachée dans un buisson",
      "Le vin blanc pétillant chaud",
      "Le shot de mezcal avec le ver au fond",
      "Le Baileys mélangé avec du jus d'orange",
      "Le mojito avec trop de menthe broyée et pas de sucre",
      "Le shot de vodka herbe de bison pure",
      "La bière artisanale trouble à 14 degrés",
      "La Manzana tiède en fin de soirée",
      "Le jeu du caps avec de la bière tiède",
      "Le shot de saké brûlant au resto chinois",
      "Le cubi de rouge qui fuit sur la nappe",
      "La bière tiède oubliée dans le coffre de la voiture",
      "Le demi de blonde industrielle coupé à l'eau",
      "Le cocktail servi dans un seau avec 10 pailles",
      "Le shot mystère offert par le barman",
      "Le mélange vodka - boisson énergisante tiède",
      "L'absinthe avec la cuillère et le sucre",
      "La margarita beaucoup trop salée sur les bords",
      "Le porto ouvert depuis 4 ans",
      "Le shot de liqueur de banane verte",
      "Le cidre brut qui sent l'étable",
      "La bière éventée au réveil",
      "Le vin chaud brûlant qui arrache la gorge",
      "Le shot de Sambuca avec le grain de café",
      "Le cocktail au shaker mal fermé qui éclabousse tout",
      "La Corona sans rondelle de citron",
      "Le digestif artisanal du tonton à 60 degrés",
      "Le shot de Limoncello pas frais",
      "Le whisky bas de gamme qui pique les yeux",
      "Le verre qui a été renversé 3 fois sur la table",
      "La bière congelée qui a explosé au freezer",
      "Le cocktail trop sucré où tu as du sirop plein les doigts",
      "Le shot de genièvre",
      "Le pack de bières qui s'éventre par terre dans la rue",
      "Le verre partagé avec 8 personnes différentes",
      "Le shot de rhum piment qui te fait pleurer",
      "Le vin d'Alsace tiède",
      "Le Gin Fizz sans bulles",
      "Le mélange douteux fait avec les restes du bar",
      "Le verre de vin rouge renversé sur un t-shirt blanc",
      "Le shooter de vodka melon chimique",
      "Le rosé pamplemousse ultra sucré",
      "Le fond de verre où quelqu'un a éteint un mégot",
      "Le cocktail au piment oiseau",
      "Le vin de table sans étiquette",
      "Le shot de pastis pur sans eau",
      "La bière éventée qui a pris le soleil",
      "Le cocktail servi dans une fausse noix de coco",
      "Le shooter de poire qui sent le dissolvant",
      "Le mélange vin rouge + Coca (Kalimotxo)",
      "Le shot bu dans le nombril de quelqu'un",
      "Le shot de tequila tiède bu à la bouteille",
      "La vodka frelatée achetée en boîte",
      "Le pichet de bière où flotte un bouchon",
      "Le verre de trop à 4h59 du matin",
      "La flûte de champagne tiède avec une fraise molle",
      "Le shot de Jagermeister bu cul-sec au goulot",
      "Le cocktail maison avec 6 alcools différents",
      "Le dernier shot avant la fermeture du bar"
    ]
  },
  dates: {
    nom: "Dates & Plans Foireux",
    description: "Les premiers rencards gênants, les pires disquettes et les comportements de charo.",
    emoji: "💔",
    hardcore: false,
    consigne_haut: "Le pire tue-l'amour",
    consigne_bas: "Ça passe encore",
    mots: [
      "Il t'emmène au kebab pour un premier date romantique",
      "Elle parle de son ex pendant 45 minutes non-stop",
      "Il divise l'addition de 14€ à 50 centimes près sur Lydia",
      "Il a les ongles sales et noirs",
      "Elle regarde son feed TikTok pendant que tu parles",
      "Il dit : 'Moi les filles je les connais par cœur'",
      "Elle t'avoue qu'elle a stalké tes parents sur LinkedIn",
      "Il essaie de t'embrasser avec les yeux grands ouverts",
      "Elle rote sans faire exprès et fait semblant de rien",
      "Il critique tes goûts musicaux dès les dix premières minutes",
      "Elle t'appelle par le prénom de son ex",
      "Il arrive avec 45 minutes de retard sans prévenir",
      "Elle te demande direct combien tu gagnes par mois",
      "Il amène son pote 'au cas où le feeling ne passe pas'",
      "Elle commande le plat le plus cher et te regarde au moment de payer",
      "Il mâche son chewing-gum la bouche grande ouverte",
      "Elle te demande l'heure exacte de ta naissance pour ton thème astral",
      "Il sent la transpiration froide mélangée au déo Axe",
      "Elle dit : 'Je te préviens, je suis toxique et possessive'",
      "Il te fait un câlin de 20 secondes super gênant au premier bonjour",
      "Elle t'envoie un pavé de reproches le lendemain du premier date",
      "Il te montre des photos de ses cartes Pokémon sans s'arrêter",
      "Elle a un rire de cochon qui s'étrangle à chaque blague",
      "Il parle de ses problèmes digestifs en plein milieu du repas",
      "Elle ne lâche pas son téléphone de toute la soirée",
      "Il met son bras autour de toi de force au cinéma",
      "Elle t'annonce qu'elle est fiancée mais 'c'est compliqué'",
      "Il t'explique la vie comme si tu avais 6 ans",
      "Elle te force à faire une photo de couple pour sa story privée",
      "Il a encore une photo de son ex en fond d'écran",
      "Elle te pose des questions comme si c'était un entretien d'embauche",
      "Il parle en voix de bébé quand il s'adresse à toi",
      "Elle mange avec les doigts dans ton assiette sans demander",
      "Il t'emmène chez ses parents pour le premier date",
      "Elle te propose d'investir dans son business de crypto",
      "Il fait un clin d'œil appuyé et gênant toutes les 5 minutes",
      "Elle te dit qu'elle a déjà choisi les prénoms de vos futurs enfants",
      "Il sent la clope froide à 3 kilomètres",
      "Elle te juge parce que tu n'as pas fait de grandes études",
      "Il essaie d'attraper ta main et rate 3 fois",
      "Elle critique le physique de toutes les personnes qui passent",
      "Il s'énerve violemment contre le serveur pour une erreur mineure",
      "Elle t'impose un silence de mort de 10 minutes sans trouver quoi dire",
      "Il a une tache de sauce tomate sur son t-shirt blanc",
      "Elle refuse catégoriquement que tu la raccompagnes même par politesse",
      "Il t'appelle 'bébé' au bout de 20 minutes de date",
      "Elle prend en photo chaque plat sous 18 angles pendant que ça refroidit",
      "Il te demande de payer son ticket de métro",
      "Elle te parle de son chat décédé en sanglotant",
      "Il a des pellicules plein les épaules",
      "Elle te dit que ses amis ont validé ton profil sur Tinder",
      "Il te fait écouter ses sons de rap amateur dans sa voiture",
      "Elle refuse de choisir quoi que ce soit et dit 'fais comme tu veux'",
      "Il te pose un lapin et te renvoie un message 3 jours plus tard",
      "Elle te demande de l'aider à déménager pour le deuxième date",
      "Il a un tatouage du prénom de son ex sur le bras",
      "Elle se recoiffe et remet du gloss toutes les 4 minutes",
      "Il te raconte ses séances de psy en détail",
      "Elle refuse de manger en public parce que 'c'est pas classe'",
      "Il te fait le coup de 'j'ai oublié ma carte, tu peux avancer ?'",
      "Elle t'avoue qu'elle a fait le date juste pour manger gratuit",
      "Il a des chaussettes trouées chez lui",
      "Elle te compare constamment à son grand amour de fac",
      "Il te fait un monologue d'une heure sur sa passion des cryptomonnaies",
      "Elle a une haleine chargée d'ail",
      "Il te demande si tu es ouvert(e) à une relation à trois dès le début",
      "Elle ne sait pas faire la conversation et répond par des monosyllabes",
      "Il se recoiffe dans le reflet de tes lunettes",
      "Elle t'envoie un message d'amour fou après 2 heures de date",
      "Il te propose de venir chez lui dès les 5 premières minutes",
      "Elle critique ta façon de t'habiller",
      "Il parle trop fort pour impressionner les tables d'à côté",
      "Elle t'avoue qu'elle est toujours amoureuse de son meilleur ami",
      "Il a une coque de téléphone jaunie et dégueulasse",
      "Elle te reproche de ne pas avoir liké sa dernière photo Insta",
      "Il fait des blagues graveleuses super lourdes",
      "Elle refuse de marcher plus de 50 mètres",
      "Il a une voix suraiguë quand il est stressé",
      "Elle fait semblant d'être au téléphone pour écourter le date",
      "Il te demande si tu comptes te marier à l'église",
      "Elle t'oblige à boire de l'alcool alors que tu ne veux pas",
      "Il t'envoie une photo de lui torse nu dans le miroir des toilettes",
      "Elle te demande de lui payer son taxi pour rentrer",
      "Il sent le parfum de contrefaçon à plein nez",
      "Elle te fait tester un produit minceur qu'elle vend",
      "Il te parle de ses gains au casino",
      "Elle t'avoue qu'elle a menti sur son âge de 5 ans",
      "Il te propose de faire un footing pour le premier date",
      "Elle ne propose même pas de participer à l'addition",
      "Il te fait des avances super insistantes dans la rue",
      "Elle a oublié ton prénom pendant le date",
      "Il te montre des vidéos TikTok gênantes en attendant ton rire",
      "Elle commente les stories d'autres mecs pendant que tu es là",
      "Il parle tout le temps de sa mère",
      "Elle te demande si tu crois aux reptiliens",
      "Il te fait monter dans sa voiture qui ressemble à une décharge",
      "Elle critique ton signe astrologique et dit que c'est un problème",
      "Il s'endort littéralement pendant le film au ciné",
      "Elle te dit que son ex était plus musclé que toi",
      "Il t'envoie un message 't'es bien rentré ?' avant même que tu aies quitté la table"
    ]
  },
  honte: {
    nom: "La Honte Absolue",
    description: "Ces moments de solitude cuisants où tu souhaites juste être téléporté sur Mars.",
    emoji: "🫣",
    hardcore: false,
    consigne_haut: "Envie de disparaître sous terre",
    consigne_bas: "Une petite gaffe sans gravité",
    mots: [
      "Envoyer le screenshot d'une conversation à la personne concernée",
      "Répondre 'merci toi aussi' au serveur qui te dit 'bon appétit'",
      "Saluer chaleureusement un inconnu qui disait bonjour à la personne derrière toi",
      "Rater une marche dans un escalier bondé et faire un plat mémorable",
      "Carte bancaire refusée 3 fois à la caisse avec 15 personnes qui attendent",
      "Avoir la braguette ouverte pendant toute une présentation orale",
      "Écouter un message vocal intime sur haut-parleur dans le train par erreur",
      "Pousser une porte vitrée où il est écrit 'TIRER' en gros",
      "Roter sans le vouloir au milieu d'un grand silence en cours ou en réunion",
      "S'asseoir sur les lunettes de quelqu'un et entendre un gros craquement",
      "Se tromper de prénom avec quelqu'un que tu connais depuis 6 mois",
      "Avoir du papier toilette collé sous la chaussure en marchant dans la rue",
      "Faire tomber tout le contenu de son sac par terre au milieu du métro",
      "Éternuer et projeter un énorme filet de bave ou de morve devant quelqu'un",
      "Dire 'bonjour' à un mannequin de magasin en plastique",
      "Entrer avec assurance dans les toilettes du mauvais sexe",
      "Liker par mégarde une photo Insta d'un ex datant de 2017 à 3h du matin",
      "Avoir un morceau de salade ou de persil coincé entre les dents de devant",
      "Se tromper de voiture sur le parking et essayer d'ouvrir la porte d'un inconnu",
      "Ton ventre qui gargouille comme un dinosaure pendant un silence total",
      "Faire semblant de rire à une blague alors que la personne racontait un drame",
      "Faire un signe de la main à un inconnu en le prenant pour un pote",
      "Craquer son pantalon au niveau des fesses en se baissant",
      "Appeler sa prof ou son patron 'Maman' sans faire exprès",
      "Faire tomber son téléphone sur le visage de quelqu'un en lui montrant une photo",
      "Marcher dans une crotte de chien juste avant d'entrer chez quelqu'un",
      "Découvrir que tu as ton t-shirt ou pull à l'envers depuis le matin",
      "Ouvrir la porte des toilettes publiques alors qu'il y a quelqu'un dedans",
      "Se prendre une porte vitrée transparente en plein visage",
      "Raconter une anecdote gênante sur quelqu'un qui est juste derrière toi",
      "Laisser échapper un pet sonore en éternuant",
      "Se faire recaler à l'entrée de la boîte devant tout son groupe de potes",
      "Confondre une femme enceinte avec quelqu'un qui a un peu de ventre",
      "Avoir une énorme auréole de sueur sous les bras lors d'un entretien",
      "Cracher par terre et le vent qui te renvoie tout sur la veste",
      "Bégayer 4 fois de suite sur le même mot simple devant 50 personnes",
      "Son alarme de téléphone qui sonne pendant un enterrement ou un examen",
      "Envoyer un message d'amour destiné à son crush dans le groupe de famille",
      "Laisser tomber sa serviette de bain devant tout le vestiaire",
      "Faire semblant de parler au téléphone et le téléphone qui se met à sonner",
      "Être le seul déguisé à une soirée parce que le thème a été annulé",
      "Rater un check avec quelqu'un et finir par lui serrer le poing",
      "Avoir du chocolat ou de la sauce plein le tour de la bouche sans le savoir",
      "Renverser son plateau repas dans le self bondé",
      "S'endormir dans le métro et se réveiller sur l'épaule d'un inconnu en bavant",
      "Chanter à tue-tête avec ses écouteurs en pensant que personne n'entend",
      "Sortir des toilettes avec sa jupe coincée dans la culotte",
      "Dire 'au revoir' à quelqu'un et marcher dans la même direction pendant 10 minutes",
      "Présenter quelqu'un en oubliant totalement son prénom au moment de le dire",
      "Rire tellement fort qu'un verre de boisson sort par le nez",
      "Se faire griller en train de se mater dans le miroir d'une vitre avec quelqu'un dedans",
      "Envoyer un vocal insultant quelqu'un au mauvais destinataire",
      "Trébucher sur ses propres lacets devant son crush",
      "Avoir une étiquette de prix géante collée sous la chaussure neuve",
      "Essayer de faire un créneau et caler 6 fois sous les yeux des passants",
      "Raconter une blague dont tu oublies la chute au milieu",
      "Avoir une trace blanche de dentifrice séchée sur le menton toute la matinée",
      "Boire un verre d'eau et s'étouffer en toussant comme un phoque",
      "Se faire attraper par la sécurité du magasin pour un antivol qui sonne par erreur",
      "Demander 'c'est qui ce mec moche sur la photo ?' et c'est le père de ton ami",
      "Envoyer un message vocal avec le micro resté allumé aux toilettes",
      "Perdre sa chaussure en courant pour attraper le bus",
      "Se cogner la tête contre le coffre de la voiture en se relevant",
      "Faire tomber une pièce de 2€ qui roule sous les pieds de tout le monde",
      "Dire 'je te rappelle' à quelqu'un qui vient de sonner à ta porte",
      "S'asseoir sur un banc avec de la peinture fraîche",
      "Son maillot de bain qui glisse à la sortie d'un toboggan aquatique",
      "Être filmé en arrière-plan d'un live télé en train de faire n'importe quoi",
      "Féliciter quelqu'un pour son anniversaire alors que c'est dans 6 mois",
      "Claquer des doigts pour appeler un serveur et faire tomber son verre",
      "Pleurer de rire au moment le plus inopportun",
      "Faire une fausse note monstrueuse au karaoké devant 100 personnes",
      "Rater un high-five et mettre une claque involontaire dans la figure",
      "Avoir des chaussettes dépareillées avec un trou béant au niveau de l'orteil",
      "L'étiquette de taille 'XXL' qui dépasse du col toute la journée",
      "S'essuyer les mains sur son pantalon et laisser des traces grasses",
      "Confondre deux jumeaux et parler de trucs intimes au mauvais",
      "Se faire surprendre en train de chanter sous la douche par les colocs",
      "Demander des nouvelles du chien de quelqu'un qui est mort il y a un an",
      "Glisser sur une feuille mouillée en essayant de courir avec classe",
      "Rester coincé dans un tourniquet de métro avec son sac",
      "Tenter un plongeon stylé et faire un plat ventral retentissant",
      "Son pantalon qui descend quand on porte un carton lourd",
      "Faire une grimace à un bébé et la mère qui te regarde méchamment",
      "Entrer dans une réunion avec 30 minutes de retard en faisant claquer la porte",
      "Laisser son partage d'écran actif pendant qu'on cherche des trucs persos",
      "Avoir sa voix qui déraille en pleine dispute ou déclaration",
      "Prendre un coup de vent qui soulève sa jupe en pleine rue",
      "Demander l'addition dans une boulangerie",
      "Se tromper d'étage et entrer chez un voisin par erreur",
      "Faire tomber sa carte d'identité dans la cuvette des toilettes",
      "Avoir du jaune d'œuf coulant sur sa chemise blanche neuve",
      "Donner un coup de pied involontaire dans un objet qui explose par terre",
      "Se tromper de rangée au cinéma et s'asseoir sur les genoux d'un inconnu",
      "Ouvrir un parapluie à l'envers sous une rafale de vent",
      "Taper dans une vitre en pensant que la porte est ouverte",
      "Mettre ses chaussures aux mauvais pieds sans s'en rendre compte",
      "Dire 'bon week-end' un mardi matin avec enthousiasme",
      "Avoir une trace de feutre indélébile sur le front toute la journée",
      "Vouloir péter discrètement et faire trembler les murs de la pièce"
    ]
  },
  reseaux: {
    nom: "Scroll Infini & Réseaux",
    description: "TikTok gênants, stories lunaires, vocaux de 4 minutes et comportements cringe en ligne.",
    emoji: "📱",
    hardcore: false,
    consigne_haut: "Le summum du malaise",
    consigne_bas: "Totalement acceptable",
    mots: [
      "Les vidéos TikTok de couples qui se filment en train de pleurer",
      "Les stories 'Posez-moi des questions' où la personne s'auto-pose des questions",
      "Les coachs en mindset de 19 ans qui t'expliquent comment devenir millionnaire",
      "Les vocaux WhatsApp de 6 minutes qui auraient pu être un message de 3 mots",
      "Les BeReal pris 14 heures en retard pour attendre d'être à une soirée",
      "Les influenceurs qui font des placements de produits pour des bonbons minceur",
      "Laisser un message en 'Vu' pendant 3 semaines et répondre comme si de rien n'était",
      "Partager ses disputes de couple en direct sur Twitter",
      "Les photos de plats avec 12 hashtags #foodporn #yummy #blessed",
      "Les messages LinkedIn du style 'Ce matin mon chien m'a appris le leadership'",
      "Les danses TikTok faites au milieu d'un couloir de métro ou supermarché",
      "Les stories Instagram avec juste un fond noir et une musique triste",
      "Les gens qui s'abonnent à toi et se désabonnent dès que tu les as follow back",
      "Les vidéos de 'prank' où on harcèle des inconnus dans la rue",
      "Mettre une photo de soi avec une citation philosophique sans rapport",
      "Les notifications 'Untel est en direct sur Instagram' à 2h du matin",
      "Les filtres Instagram qui te transforment complètement le visage",
      "Les groupes WhatsApp de 40 personnes où 2 personnes parlent de leur vie",
      "Les stories 'close friends' utilisées uniquement pour tailler ses potes",
      "Filmer tout un concert entier avec son flash allumé devant les autres",
      "Les messages 'Coucou, j'ai une super opportunité de business pour toi'",
      "Les vidéos 'Get Ready With Me' de 25 minutes où rien ne se passe",
      "Afficher sa flamme Snapchat de 1200 jours comme un trophée",
      "Les threads Twitter inventés de toutes pièces pour faire du buzz",
      "Mettre son compte en privé, puis en public, puis en privé chaque semaine",
      "Les photos de pieds vendues sur Vinted sous prétexte de vendre des chaussures",
      "Les lives TikTok de gens qui font les robots (NPC)",
      "Les photos de salle de sport avec la légende 'No pain no gain'",
      "Spoil une série sur Twitter 10 minutes après la sortie de l'épisode",
      "Répondre uniquement avec des mèmes dépassés depuis 2016",
      "Les reels Instagram avec une voix robotique insupportable",
      "Mettre des sondages en story : 'Vous préférez ce t-shirt en bleu ou en noir ?'",
      "Supprimer une photo parce qu'elle n'a pas fait assez de likes en 15 minutes",
      "Les influenceurs qui simulent une agression pour avoir des vues",
      "Mettre son QR code Lydia ou PayPal dans sa bio Twitter",
      "Les messages vocaux chuchotés parce qu'il y a du monde à côté",
      "Les vidéos de dégustation avec bruits de mastication amplifiés (ASMR)",
      "Stalker l'ex de son crush jusqu'à remonter à ses photos de 2014",
      "Les profils Tinder avec uniquement des photos de groupe",
      "Les stories Insta de thermomètre quand la personne a 38° de fièvre",
      "S'inventer une vie de riche dans les commentaires TikTok",
      "Les trends où tout le monde fait exactement la même blague pendant 3 semaines",
      "Les vidéos de motivation avec des images de loups ou Peaky Blinders",
      "Envoyer 'Faut que je te dise un truc' et disparaître pendant 5 heures",
      "Commenter 'Premier' sous chaque vidéo YouTube",
      "Les influenceurs qui pleurent face caméra sans verser une seule larme",
      "Les photos de billet d'avion pour prouver qu'on part en vacances",
      "Créer un compte Instagram pour son animal de compagnie",
      "Les tests de personnalité bidons partagés sur Facebook",
      "Les chaînes de messages 'Renvoie ça à 10 personnes sinon malheur'",
      "Partager sa rétrospective Spotify 50 fois en story",
      "Les DM Insta qui commencent par juste 'Salut' sans rien d'autre",
      "Les vidéos où quelqu'un coupe du savon sous une voix off",
      "Créer un groupe pour chaque micro-événement de sa vie",
      "Les photos avec la localisation 'Dans ton cœur' ou 'Chez moi'",
      "Les unboxings de colis Shein de 40 kilos",
      "Filmer les gens à la salle pour les accuser de regarder",
      "Reposter des avis de recherche faux datant de 2012",
      "Les tweets du style 'Je dis ça je dis rien'",
      "Les lives Insta entre influenceurs qui n'ont rien à se dire",
      "Mettre en bio 'CEO / Entrepreneure' alors qu'on vend des bougies",
      "Les photos de jambes au bord d'une piscine façon saucisses",
      "Les stories de concerts où le son sature complètement et grésille",
      "Les messages vocaux envoyés en plein vent où on n'entend rien",
      "Les vidéos de danse gênante avec ses parents pour percer",
      "Taguer 35 potes sur un mème pas drôle",
      "Les profils avec des photos générées par IA qui ne ressemblent à rien",
      "Les stories d'anniversaire avec 40 collages de photos dossier",
      "Les comptes fan obsessionnels d'une célébrité",
      "Demander de voter pour son concours par message privé",
      "Les vlogs de rentrée scolaire à 25 ans",
      "Les captures d'écran de conversations privées postées sans masquer les noms",
      "Changer son statut relationnel Facebook en 'C'est compliqué'",
      "Les trends TikTok avec des bruits de pets rajoutés",
      "Les faux dramas organisés pour vendre des formations",
      "Créer un faux compte pour espionner son ex",
      "Les boîtes à lettres anonymes NGL pour s'envoyer des compliments",
      "Se filmer au volant à 130 km/h pour montrer le compteur",
      "Les vidéos de réveil à 5h du matin avec un bain glacé",
      "Répondre 'mdr' sans esquisser le moindre sourire",
      "Les concours bidons avec un iPhone jamais envoyé",
      "Les stories privées avec 250 personnes dedans",
      "Les messages vocaux de gens qui respirent fort dans le micro",
      "Relancer quelqu'un avec un simple point d'interrogation '?' au bout de 20 min",
      "Les commentaires haineux anonymes sous les vidéos",
      "Utiliser encore le filtre chien de Snapchat",
      "Les photos de bouquet de fleurs sans dire qui l'a offert pour faire planer le doute",
      "Les vidéos de gens qui mangent des quantités astronomiques de fast-food",
      "Les faux avis positifs rédigés par les créateurs eux-mêmes",
      "Demander de partager sa cagnotte Leetchi pour son voyage perso",
      "Les comptes Insta de bébés où les parents parlent à leur place",
      "Les stories cryptiques : 'Ne faites confiance à personne...'",
      "Se filmer en train de donner 5€ à un SDF pour le buzz",
      "Mettre 'Pas de temps à perdre' dans sa bio Tinder",
      "Les filtres qui rajoutent de fausses taches de rousseur géantes",
      "Les threads Twitter qui se terminent par '1/48'",
      "Les vidéos avec la musique 'Oh no, oh no, no no no no'",
      "Mettre son signe astrologique dans son pseudo",
      "Les vidéos d'excuses d'influenceurs de 40 minutes sans maquillage",
      "Envoyer des invitations de jeux Facebook en 2026"
    ]
  },
  deche: {
    nom: "La Dèche & Vies de Galère",
    description: "Le compte à -20€ dès le 12 du mois, les calculs de centimes et les astuces de rat.",
    emoji: "💸",
    hardcore: false,
    consigne_haut: "Le pire radin / La pire dèche",
    consigne_bas: "Totalement justifié",
    mots: [
      "Manger des pâtes au beurre et sel du 12 au 30 du mois",
      "Réclamer 0,75€ sur Lydia à un ami pour un café",
      "Commander Uber Eats avec ses 15 derniers euros sur son compte bancaire",
      "Recharger son téléphone dans les gares pour économiser l'électricité",
      "Couper le tube de dentifrice en deux pour racler le fond",
      "Prendre 25 sachets de sauce gratuits chez McDo pour chez soi",
      "Partir du resto en douce au moment de payer l'addition",
      "Remplir sa gourde dans les toilettes d'un bar pour ne pas payer 4€",
      "Mettre de l'eau dans le flacon de liquide vaisselle pour le faire durer 3 mois",
      "Acheter le jambon premier prix avec 30% d'eau dedans",
      "Demander le code Wi-Fi du voisin au lieu de payer une box",
      "Réutiliser ses vieux sachets de thé deux ou trois fois",
      "Faire semblant d'avoir oublié son portefeuille quand l'addition arrive",
      "Prendre des rouleaux de papier toilette à la fac ou au boulot pour chez soi",
      "Rentrer à pied pendant 1h30 sous la pluie pour économiser un ticket de métro",
      "Scanner un avocat comme des oignons à la caisse automatique",
      "Se faire refuser sa carte bancaire pour un achat de 1,20€ à la boulangerie",
      "Garder un meuble cassé trouvé sur le trottoir pendant 4 ans",
      "Manger des conserves périmées depuis 2021 parce que la boîte n'est pas bombée",
      "Acheter les fruits et légumes au rabais qui sont déjà tout mous",
      "Ne jamais chauffer son appart en hiver et dormir avec 3 couettes et un bonnet",
      "Squatter le compte Netflix d'un ex qui n'a jamais changé le mot de passe",
      "Demander de diviser l'addition au centime après avoir bu 4 verres de plus",
      "Boire l'eau des pâtes en guise de bouillon chaud",
      "Mettre des serviettes en papier du fast-food en guise de papier toilette",
      "Faire ses courses exclusivement au rayon 'anti-gaspi' date courte",
      "Partager une pizza surgelée à trois personnes",
      "Ne pas aller chez le dentiste pendant 5 ans pour économiser",
      "Se doucher à la salle de sport uniquement pour ne pas payer d'eau chaude chez soi",
      "Ramener son propre sandwich et sa canette au cinéma",
      "Diluer le shampoing avec de l'eau tiède pour finir la bouteille",
      "Récupérer les tickets de caisse par terre pour chercher des réductions",
      "Refuser de laisser un pourboire de 50 centimes à un livreur sous la neige",
      "Manger du riz blanc avec seulement un bouillon cube émietté dessus",
      "Prendre les stylos et carnets de tous les hôtels où l'on passe",
      "Acheter des fringues sur Vinted à 1€ et négocier à 0,80€",
      "Emprunter la voiture d'un pote et la rendre avec le voyant de réserve allumé",
      "Utiliser du savon pour les mains en guise de gel douche et lessive",
      "Manger des biscuits apéro rassis trouvés au fond d'un placard",
      "Attendre les soldes pour acheter un paquet de chaussettes",
      "Prendre toutes les dosettes de sucre et de sel dans les cafés",
      "Rester dans un appart moisi parce que le loyer est 30€ moins cher",
      "Regarder un match de foot à travers la vitre d'un bar sans y entrer",
      "Acheter du soda premier prix sans bulles au goût chimique",
      "Ne jamais allumer la lumière et vivre à la lueur de l'ordinateur",
      "Rendre un vêtement après l'avoir porté tout un week-end avec l'étiquette cachée",
      "Récupérer les canettes en métal pour les revendre",
      "Manger une boîte de maïs entière directement à la cuillère pour tout repas",
      "Dire 'je n'ai pas très faim' au resto pour ne manger que la corbeille de pain",
      "Laver son linge à la main dans le lavabo pour économiser la laverie",
      "Éviter d'inviter des potes chez soi de peur qu'ils boivent tes boissons",
      "Utiliser un essuie-tout comme filtre à café",
      "Garder les vieux pots de confiture vides pour en faire des verres",
      "Acheter des chaussures avec une pointure en trop parce qu'elles étaient à -70%",
      "Prendre un forfait mobile à 2€ et squatter tous les Wi-Fi publics",
      "Remplir ses poches de nourriture au buffet à volonté",
      "Ne jamais acheter de sacs poubelle et utiliser les sachets des courses",
      "Boire le reste de café froid de la cafetière de la veille",
      "Attendre que le serveur tourne le dos pour piquer le pain de la table voisine",
      "Gratter les pots de Nutella avec le manche d'une cuillère pendant 20 minutes",
      "Refuser d'allumer le ventilateur pendant la canicule pour économiser l'électricité",
      "Partager un compte Spotify famille avec des inconnus sur internet",
      "Utiliser un vieux t-shirt troué comme serviette de bain",
      "Ne jamais aller chez le coiffeur et se couper les pointes tout seul",
      "Acheter de la pâte à tartiner premier prix sans goût de noisette",
      "Demander à être remboursé d'un chewing-gum",
      "Calculer le prix au kilo de chaque aliment au supermarché pendant 2 heures",
      "Rouler sur la réserve d'essence pendant 40 kilomètres en priant",
      "Conserver les serviettes en papier usagées si elles sont peu sales",
      "Se nourrir exclusivement d'échantillons gratuits sur les marchés",
      "Prendre un train de nuit sans couchette pour économiser une nuit d'hôtel",
      "Ne pas tirer la chasse d'eau à chaque fois pour économiser l'eau",
      "Emprunter un chargeur de téléphone et oublier de le rendre",
      "Manger des flocons d'avoine avec de l'eau tiède du robinet",
      "Acheter des lunettes de soleil à 2€ sur le marché qui déforment la vue",
      "Partir en vacances en camping sauvage sur un rond-point",
      "Demander un verre d'eau du robinet et 4 tranches de citron gratuites au bar",
      "Refuser de participer à la cagnotte d'anniversaire d'un ami proche",
      "Acheter un paquet de cigarettes à deux et compter le nombre de taffes",
      "Dormir sur un matelas gonflable crevé pendant six mois",
      "Réparer ses semelles de chaussures avec du scotch de déménagement",
      "Faire les poubelles des supermarchés après la fermeture",
      "Proposer d'échanger des tickets resto contre du liquide à ses collègues",
      "Garder les vieilles piles usagées en les mordant pour qu'elles remarchent",
      "Remplir son flacon de parfum avec les testeurs chez Sephora",
      "Manger des biscottes cassées parce qu'elles étaient en promo",
      "Demander à payer en 4 fois sans frais un achat de 30€",
      "Se faire héberger sur le canapé d'un pote pendant 3 mois d'affilée",
      "Ne jamais acheter d'essuie-tout et s'essuyer avec ses manches",
      "Boire de l'eau chaude avec du sucre pour calmer la faim",
      "Faire sécher ses sachets de thé au soleil sur le balcon",
      "Refuser de payer le pourboire dans un pays étranger",
      "Acheter des éponges premier prix qui se déchirent en deux utilisations",
      "Mettre du scotch sur son câble de chargeur dénudé qui fait des étincelles",
      "Rentrer en boîte de nuit en passant par la sortie de secours",
      "Payer une baguette de pain entièrement en pièces de 1 et 2 centimes",
      "Avoir un solde bancaire de -0,42€ et paniquer à chaque notif",
      "Faire des faux retours sur Amazon pour se faire rembourser l'article",
      "Ne pas acheter de poêle et cuire ses steaks sur du papier alu",
      "Remplir sa poche de glaçons au bar pour les ramener chez soi"
    ]
  },
  flemme: {
    nom: "Flemme Légendaire",
    description: "Annuler une soirée pour végéter au lit, vaisselle fossilisée et flemme de respirer.",
    emoji: "🛋️",
    hardcore: false,
    consigne_haut: "Le roi des larves",
    consigne_bas: "Un repos mérité",
    mots: [
      "Annuler une soirée 10 minutes avant avec un mytho bidon pour rester au lit",
      "Laisser tremper une poêle dans l'évier pendant 5 jours",
      "Regarder un film en langue étrangère sans sous-titres parce que la télécommande est trop loin",
      "Commander Uber Eats pour un resto en bas de son immeuble",
      "Mettre du déodorant par-dessus la transpiration pour éviter la douche",
      "Porter le même jogging 7 jours d'affilée sans honte",
      "Manger des céréales directement dans le carton avec les mains",
      "Jeter ses vêtements sur 'la chaise à fringues' jusqu'à ce qu'elle croule",
      "Se retenir d'aller aux toilettes pendant 3 heures pour ne pas quitter son lit",
      "Faire défiler TikTok pendant 4 heures alors qu'on avait dit 'juste 5 minutes'",
      "Balayer la poussière directement sous le tapis",
      "Dormir sans draps directement sur le matelas nu pour ne pas enfiler de housse",
      "Manger son plat froid pour ne pas attendre 2 minutes devant le micro-ondes",
      "Répondre juste 'OK' ou un emoji pouce pour couper court à toute conversation",
      "Laisser le linge mouillé dans la machine à laver pendant 3 jours",
      "Faire glisser un objet tombé avec le pied au lieu de se baisser",
      "Manger ses pâtes à même la casserole avec une cuillère en bois",
      "Préférer mourir de soif plutôt que de se lever chercher un verre d'eau",
      "Mettre ses chaussettes à l'envers par flemme de les retourner",
      "Allumer ou éteindre la lumière avec le pied depuis son lit",
      "Choisir ses habits parmi ceux qui traînent déjà par terre",
      "Regarder 4 épisodes d'une série nulle juste parce qu'elle s'est lancée toute seule",
      "Faire semblant de ne pas entendre la sonnette pour ne pas ouvrir",
      "Mettre ses poubelles sur le balcon pour ne pas descendre les jeter",
      "Dormir tout habillé pour être déjà prêt pour le lendemain matin",
      "Boire l'eau directement au robinet pour ne pas laver de verre",
      "Ne jamais défaire sa valise de vacances et piocher dedans pendant un mois",
      "Laisser le carton de livraison Amazon au milieu de l'entrée pendant des semaines",
      "Préférer avoir froid plutôt que de se lever pour fermer la fenêtre",
      "Pousser la vaisselle sale sur le côté pour poser une tasse",
      "Mettre un mot de passe à 1 seul caractère pour taper plus vite",
      "Ne pas ouvrir son courrier pendant 6 mois de peur d'avoir un truc à gérer",
      "Utiliser un seul couteau pour beurrer, couper et touiller son café",
      "Rester assis par terre parce que le canapé est couvert de linge propre pas plié",
      "Acheter des caleçons neufs pour éviter de lancer une machine",
      "Répondre uniquement par des vocaux parce que taper au clavier est trop fatiguant",
      "Faire couler la douche chaude pendant 10 minutes avant de se motiver à y aller",
      "Manger une boîte de thon ou maïs avec les doigts pour ne pas salir de fourchette",
      "Faire semblant de dormir quand quelqu'un entre dans la pièce",
      "Déchirer un emballage avec les dents plutôt que de chercher des ciseaux",
      "Reporter une mise à jour d'ordinateur pendant 8 mois d'affilée",
      "Laisser les décorations de Noël dans le salon jusqu'au mois de juillet",
      "Manger du pain dur plutôt que de marcher 3 minutes jusqu'à la boulangerie",
      "S'endormir avec la lumière allumée parce que l'interrupteur est trop loin",
      "Ne jamais plier ses chaussettes et les jeter en vrac dans un tiroir",
      "Dire 'j'arrive' alors qu'on est encore en sous-vêtements sous la couette",
      "Mettre du parfum d'ambiance sur ses vêtements pour masquer l'odeur",
      "Prendre un taxi pour faire un trajet de 400 mètres",
      "Poser le nouveau rouleau de papier toilette directement sur l'ancien tube vide",
      "Écouter une musique insupportable en boucle parce que le téléphone est trop loin",
      "Laisser un colis repartir à l'expéditeur par flemme d'aller au point relais",
      "Préférer rater un rendez-vous chez le médecin plutôt que d'annuler au téléphone",
      "Regarder le plafond pendant 1 heure sans rien faire plutôt que de faire une corvée",
      "Pousser les miettes sous la table au lieu de passer une éponge",
      "Changer de chaîne de télé avec le gros orteil",
      "Boire le café froid de la veille plutôt que d'en faire un frais",
      "Attendre que quelqu'un d'autre se lève pour lui demander de rapporter un truc",
      "Mettre des lunettes de soleil toute la journée pour cacher sa tête de déterré",
      "Manger dans une assiette en carton pour ne rien avoir à laver",
      "Rester dans son bain jusqu'à ce que l'eau soit glacée par flemme d'en sortir",
      "Écrire sans ponctuation ni majuscules pour taper moins sur le clavier",
      "Ne pas vider le bac de l'aspirateur pendant un an",
      "Laisser 15 000 mails non lus s'accumuler dans sa boîte de réception",
      "S'habiller en noir pour ne pas avoir à réfléchir aux couleurs",
      "Faire une sieste de 4 heures et se réveiller encore plus fatigué",
      "Manger des nuggets à peine décongelés parce qu'on a faim tout de suite",
      "Déposer un objet dans l'escalier en attendant que quelqu'un d'autre le monte",
      "Faire semblant de ne pas avoir de réseau pour esquiver un appel",
      "Mettre ses baskets sans défaire les lacets en écrasant complètement le talon",
      "Rester dans le noir quand la nuit tombe parce qu'on a la flemme d'allumer",
      "Manger des chips avec une pince pour ne pas avoir les doigts gras sur l'écran",
      "Garder 70 onglets ouverts sur son navigateur depuis 6 mois",
      "Dire au livreur de laisser le colis dans le hall par flemme de descendre",
      "Ne jamais faire son lit parce qu'on va s'y recoucher le soir même",
      "Se laver uniquement le visage au gant pour aller plus vite",
      "Manger une pomme entière avec le trognon pour ne pas aller jusqu'à la poubelle",
      "Payer un abonnement inutile de 10€ par mois plutôt que de chercher comment résilier",
      "Garder une écharpe en intérieur pour ne pas avoir à se raser",
      "Choisir le tout premier résultat Google sans chercher plus loin",
      "S'endormir sur le canapé avec ses baskets encore aux pieds",
      "Laisser un insecte mort sur le rebord de la fenêtre pendant 6 mois",
      "Mettre le chauffage à fond au lieu d'enfiler un gilet",
      "Faire semblant d'être malade pour esquiver un repas de famille",
      "Manger ses tartines posées directement sur la table sans assiette",
      "Garder ses lentilles de contact 48 heures par flemme de les retirer",
      "Utiliser la dictée vocale même dans la rue pour ne pas taper",
      "Ne jamais arroser une plante jusqu'à ce qu'elle devienne complètement sèche",
      "Préférer rater son train plutôt que de courir 20 secondes",
      "Se brosser les dents pendant 12 secondes avant de filer au lit",
      "Mettre une casquette ou un bonnet pour cacher ses cheveux gras",
      "Prendre l'ascenseur pour descendre un seul étage",
      "Manger du fromage râpé directement à la poignée dans le sachet",
      "Ne pas ranger ses courses et laisser les sacs au milieu du salon",
      "Rester sous la douche jusqu'à ce qu'il n'y ait plus une seule goutte d'eau chaude",
      "S'endormir en se promettant de tout faire demain matin à la première heure",
      "Utiliser une chaise comme penderie pendant 6 mois",
      "Dormir en travers du lit parce que l'autre moitié est pleine d'affaires",
      "Manger des raviolis froids directement dans la boîte de conserve",
      "Regarder le générique de fin en entier parce qu'on a la flemme d'éteindre",
      "Faire semblant d'être occupé sur son téléphone pour ne pas aider à débarrasser la table"
    ]
  },
  culinaire: {
    nom: "Crimes Culinaires",
    description: "De quoi se fâcher définitivement autour d'une table. Assumez vos pires goûts.",
    emoji: "🍕",
    hardcore: false,
    consigne_haut: "Le pire crime",
    consigne_bas: "Le plus pardonnable",
    mots: [
      "L'ananas sur la pizza",
      "Tremper ses tartines dans le café",
      "Le Ketchup sur les pâtes",
      "Manger la peau du saucisson",
      "La coriandre (goût de punaise)",
      "Tremper ses frites dans la glace (Sundae)",
      "La viande très bien cuite",
      "Le lait avant les céréales",
      "Le boudin noir",
      "Le foie de veau",
      "Les tripes",
      "La cervelle",
      "Le jus de tomate dans l'avion",
      "Les choux de Bruxelles",
      "Mettre des glaçons dans le vin rouge",
      "La pizza aux fruits de mer",
      "Les bonbons à la réglisse",
      "Manger son burger avec des couverts",
      "Le McDo froid le lendemain",
      "Les endives au jambon",
      "Croquer dans un oignon cru",
      "Le fromage à tartiner avec de la confiture",
      "Couper ses spaghettis au couteau",
      "Mettre de la crème dans la Carbonara",
      "Manger une pomme en faisant beaucoup de bruit",
      "Le chocolat blanc",
      "Le Coca sans bulles",
      "Manger la croûte du fromage",
      "Le surimi chaud",
      "La mayonnaise avec les frites",
      "Tremper son croissant dans du jus d'orange",
      "Les gâteaux aux fruits confits",
      "Les huîtres chaudes",
      "Le sandwich triangle de l'autoroute",
      "L'eau gazeuse tiède",
      "La menthe dans les plats salés",
      "Les frites molles",
      "Manger des glaçons",
      "Les sushis au fromage",
      "Mettre du sucre sur ses pâtes",
      "Le beurre doux (sans sel)",
      "Les champignons en boîte",
      "Le lait ribot",
      "Manger du Nutella à la cuillère",
      "Les saucisses Zwan en boîte",
      "Le ketchup sur le steak",
      "Les frites avec une fourchette",
      "Le beurre de cacahuète",
      "Les raviolis en boîte mangés froids",
      "Le thé glacé en bouteille",
      "Le camembert trempé dans le café",
      "La glace saveur Schtroumpf",
      "Le Nutella avec du fromage de chèvre",
      "La pizza hawaïenne froide du frigo",
      "Les pâtes trop cuites qui forment un bloc",
      "Le steak tartare tiède",
      "Mettre de l'eau dans le vin",
      "Les huîtres trempées dans le ketchup",
      "Les bonbons piments ultra forts",
      "Le tacos 3 viandes avec frites à l'intérieur",
      "Les makis banane Nutella",
      "Les cornichons dans le Nutella",
      "La raclette sans charcuterie",
      "Le pain de mie trempé dans l'eau",
      "Les lasagnes brûlantes dehors et congelées au milieu",
      "Le cordon bleu décongelé à la poêle tout mou",
      "Les frites trempées dans le milkshake",
      "La pizza au chocolat",
      "Le Coca tiède sans gaz",
      "Manger une boîte de thon nature à même la conserve",
      "Les nuggets froids de la veille",
      "Le lait caillé",
      "La croûte de pizza laissée dans l'assiette",
      "Le jaune d'œuf qui dégouline sur les doigts",
      "Le riz trop cuit en bouillie collante",
      "La mayonnaise sur des pâtes au beurre",
      "La sauce barbecue sur du poisson",
      "Manger les pépins de pomme",
      "Les chips au vinaigre qui brûlent la langue",
      "Les haricots blancs à la tomate au petit déjeuner",
      "Le tofu nature sans assaisonnement",
      "Le café réchauffé 3 fois au micro-ondes",
      "Les fruits de mer élastiques décongelés",
      "La soupe froide en hiver",
      "Manger des pâtes sans aucune matière grasse ni sauce",
      "Le saucisson avec la peau en plastique",
      "Le beurre salé sur du Nutella",
      "Les champignons de Paris crus",
      "Le Coca Zero qui n'a aucun goût",
      "Le foie gras avec du ketchup",
      "Les escargots au beurre persillé",
      "La salade verte qui baigne dans le vinaigre blanc",
      "Les carottes râpées industrielles trop acides",
      "Le kebab sans frites",
      "Les crêpes salées au sucre",
      "Boire le jus du bocal de cornichons",
      "Les gnocchis crus ou pas cuits à cœur",
      "Le fromage maroilles au petit déjeuner",
      "Les bonbons qui piquent jusqu'à saigner de la langue",
      "La pizza trempée dans la sauce piquante jusqu'à être rouge"
    ]
  },
  redflag: {
    nom: "Red Flag",
    description: "Ces petits comportements sociaux qui donnent envie de fuir très loin.",
    emoji: "🚩",
    hardcore: false,
    consigne_haut: "Le plus toxique",
    consigne_bas: "Le plus acceptable",
    mots: [
      "Parle mal aux serveurs au resto",
      "Ne pose absolument aucune question sur toi",
      "Reste hyper pote avec tous ses ex",
      "Dit souvent : 'Je suis entier, je dis ce que je pense'",
      "Claque des doigts pour appeler quelqu'un",
      "Met son téléphone sur haut-parleur dans le bus",
      "Mâche la bouche ouverte",
      "Ne lit jamais de livres",
      "Ne dit pas merci quand tu tiens la porte",
      "Coupe tout le temps la parole",
      "Ramène toujours toutes les histoires à lui/elle",
      "Juge tes passions de geek",
      "Est toujours en retard sans prévenir",
      "Te fait du gaslighting",
      "Refuse catégoriquement de s'excuser",
      "Crie pour avoir raison dans un débat",
      "Suit le GPS sans regarder la route",
      "N'aime pas les animaux",
      "A les ongles longs et sales",
      "Fait des vocaux au milieu du métro bondé",
      "Critique ses potes dans leur dos",
      "Tape sur son écran ou sa manette quand il perd",
      "Ne se lave pas les mains en sortant des toilettes",
      "Garde ses chaussettes sales au lit",
      "Renifle au lieu de se moucher",
      "Se gare sur les places handicapés 'juste 2 minutes'",
      "Fait des blagues méchantes sous prétexte d'humour",
      "Ne boit jamais d'eau, que des sodas",
      "A une hygiène dentaire douteuse",
      "T'explique des choses que tu sais déjà",
      "Poste des citations de motivation sur Insta",
      "Répond 'OK' à un long message touchant",
      "Laisse son caddie au milieu du parking",
      "Spoil la fin des films et séries sans prévenir",
      "Ne propose jamais de payer ou partager l'addition",
      "Marche hyper lentement devant toi dans la rue",
      "Te fixe dans les yeux sans cligner quand tu parles",
      "Ne recycle absolument rien",
      "T'appelle sans envoyer de message avant",
      "Met des lunettes de soleil en boîte de nuit",
      "Dit 'comme même' au lieu de 'quand même'",
      "Applaudit quand l'avion atterrit",
      "Affiche ses disputes de couple sur les réseaux",
      "Prend toute la place dans le lit en étoile de mer",
      "Te demande ton signe astrologique à la première phrase",
      "Répond uniquement avec des stickers",
      "Ne ramène jamais rien quand il est invité",
      "Parle très fort au téléphone au restaurant",
      "Dit 'je ne suis pas comme les autres'",
      "Ne tient jamais ses promesses",
      "Met ses conversations en mode éphémère sur WhatsApp",
      "A une photo de profil avec une liasse de billets",
      "Dit 'je ne m'entends pas avec les filles, trop d'histoires'",
      "A une liste secrète de ses conquêtes dans ses notes",
      "Ne laisse jamais aucun pourboire même quand le service est parfait",
      "Regarde ses messages pendant que tu lui racontes un truc grave",
      "Te reproche un truc qu'il a rêvé cette nuit",
      "Follow 3000 personnes sur Insta et a 80 abonnés",
      "Vérifie discrètement ton écran quand tu reçois une notif",
      "Dit 'toutes mes ex étaient des folles'",
      "Se vante de ne jamais payer le train ou les transports",
      "Prend des photos de toi sans ton accord pour les mettre en story",
      "Met 4 jours à répondre mais poste 15 stories par jour",
      "Change complètement de personnalité devant ses potes",
      "Dit 'moi je suis honnête, je blesse mais c'est la vérité'",
      "A encore les photos de son ex sur son feed Insta",
      "Parle de son salaire au bout de 5 minutes de discussion",
      "Crache par terre dans la rue",
      "Se regarde dans toutes les vitrines de magasins",
      "Te demande de lui rembourser un café à 1€50",
      "N'a aucun ami d'enfance",
      "Emprunte tes fringues et ne les rend jamais",
      "Fait la gueule pendant des heures sans dire pourquoi",
      "Se vante de conduire vite ou sans permis",
      "Rigole fort à ses propres blagues quand personne ne rit",
      "Jette ses mégots ou ses canettes par terre",
      "T'appelle en numéro masqué pour voir si tu réponds",
      "Te critique gentiment devant les autres pour se valoriser",
      "Ne retient jamais le prénom de tes potes",
      "Dit 'tu es trop sensible' quand tu lui dis ce qui ne va pas",
      "Garde son casque audio sur les oreilles pendant que tu parles",
      "Fait semblant d'avoir oublié son portefeuille au resto",
      "Dit 'les pauvres n'ont qu'à travailler plus'",
      "Refuse catégoriquement de goûter un plat qu'il ne connaît pas",
      "Te supprime et te re-follow pour attirer ton attention",
      "Se vante d'avoir brisé des cœurs",
      "T'envoie un vocal de 7 minutes pour un oui ou un non",
      "Dit 'si tu m'aimais vraiment, tu ferais ça'",
      "A un casier judiciaire et trouve ça valorisant",
      "Parle en acronymes d'entreprise (ASAP, KPI, feedback)",
      "Ne dit jamais bonjour aux caissiers ou chauffeurs Uber",
      "Prend le dernier morceau sans demander à la table",
      "Prend parti pour ton ennemi pour faire l'avocat du diable",
      "Envoie 't'es réveillé ?' à 3h42 du matin",
      "Ne lave jamais ses draps",
      "T'offre un cadeau qu'on lui a offert l'année passée",
      "Met son téléphone face cachée dès que tu t'assois",
      "Se victimise dans 100% de ses histoires",
      "Dit 'je ne bois pas d'eau, l'eau ça rouille'",
      "Se prend en photo en train de pleurer pour les réseaux"
    ]
  },
  malaise: {
    nom: "Mode hardcore",
    description: "Attention, mots hardcore. Rien que de les lire et de les classer, vous allez grincer des dents.",
    emoji: "😖",
    hardcore: true,
    consigne_haut: "Le plus insoutenable",
    consigne_bas: "Le plus supportable",
    mots: [
      "Smegma",
      "Un pet vaginal",
      "Cyprine",
      "Furoncle suintant",
      "La chiasse",
      "Le mot 'Humide'",
      "Des glaires",
      "Un ongle incarné",
      "Sentir le cul",
      "Un mollard",
      "Une mycose",
      "Le mot 'Pénétrer'",
      "Visqueux",
      "Turgescent",
      "Dégobiller",
      "Un bouton blanc prêt à percer",
      "Du pus",
      "Foutre",
      "Un étron",
      "La chaude-pisse",
      "Des hémorroïdes",
      "Éjaculat",
      "Roter dans la bouche de quelqu'un",
      "Renifler un pet",
      "Un tampon usagé",
      "Un morpion",
      "Suinter",
      "Mastication bruyante (l'entendre)",
      "Croûte de lait",
      "Le gland",
      "Un filet de bave",
      "Des poils pubiens dans le lavabo",
      "Frotter",
      "La raie du maçon transpirante",
      "Une odeur de pieds vinaigrée",
      "Avaler de travers",
      "Un grumeau dans le lait",
      "Mucus",
      "Sécrétion",
      "Fécal",
      "Transpiration rance",
      "Manger ses crottes de nez",
      "Se ronger les peaux mortes",
      "Gingivite",
      "Haleine de café froid",
      "Salive épaisse",
      "Un cheveu dans la soupe",
      "Avoir la courante",
      "Lubrifiant",
      "Pustule",
      "Un crachat qui atterrit près de toi",
      "Des pellicules sur un pull noir",
      "La peau qui pèle après un coup de soleil",
      "Le bruit d'une dent qui craque",
      "Un poil incarné purulent",
      "Du vomi séché dans les cheveux",
      "Une vieille éponge qui pue la mort",
      "Boire par erreur le fond d'une canette qui servait de cendrier",
      "L'odeur des égouts par 35 degrés",
      "Un cafard qui te vole dessus",
      "Les doigts qui sentent la crevette périmée",
      "Un escargot écrasé pieds nus",
      "Une chaussette mouillée dans une flaque sale",
      "Un rot à l'odeur d'œuf pourri",
      "Des croûtes de boutons arrachées",
      "Un abcès dentaire suintant",
      "Du sang de nez sur un t-shirt blanc",
      "Une haleine de tabac froid au réveil",
      "Des ongles de pieds trop longs et jaunis",
      "Une cuvette de toilettes encore chaude",
      "Un cheveu coincé au fond de la gorge",
      "De la morve sèche sur la manche",
      "Une limace baveuse sur la salade",
      "Des asticots qui grouillent dans la poubelle",
      "L'odeur de friture rance incrustée sur un manteau",
      "Des traces de doigts grasses sur les verres de lunettes",
      "Un slip retourné pour être porté deux fois",
      "Le jus au fond du sac poubelle qui coule sur la jambe",
      "Un morceau de viande coincé entre deux dents depuis 2 jours",
      "Une compresse qui colle à une plaie",
      "De la moisissure verte sur le pain de mie",
      "Un chien qui te lèche la bouche après s'être léché le derrière",
      "Une douche collective avec de l'eau stagnante",
      "Un chewing-gum mâché collé sous une table",
      "La sueur qui coule entre les fesses en été",
      "L'odeur d'un vestiaire après un match",
      "De la corne de pied qui s'effrite",
      "Une ampoule percée sous le pied",
      "Une morsure de tique gonflée",
      "Un bouton de fièvre qui suinte",
      "Une dent qui bouge et qui fait un cliquetis",
      "De la bouillie tiède régurgitée par un bébé",
      "Une haleine d'ail de la veille",
      "Des poils dans la plaquette de beurre",
      "Une trace de frein au fond du caleçon",
      "Un écoulement nasal purulent",
      "Le bruit d'un os qui craque violemment",
      "De la crasse noire sous les ongles",
      "Une vieille boîte de Tupperware oubliée 3 mois au frigo",
      "Une limace écrasée sous le pied nu dans l'herbe"
    ]
  },
  melimelo: {
    nom: "Thème général",
    description: "Regroupe toutes les catégories hors hardcore pour un mélange totalement imprévisible !",
    emoji: "🌀",
    special: true,
    hardcore: false,
    consigne_haut: "Je préfère",
    consigne_bas: "Je préfère le moins"
  }
};

// Vérification du nombre de mots
console.log('--- VÉRIFICATION DES THÈMES ---');
let totalMots = 0;
for (const [cle, data] of Object.entries(THEMES)) {
  if (data.mots) {
    const uniques = Array.from(new Set(data.mots));
    console.log(`${data.emoji} ${data.nom} (${cle}) : ${uniques.length} mots uniques`);
    totalMots += uniques.length;
    data.mots = uniques; // garantir l'absence de doublons
  } else {
    console.log(`${data.emoji} ${data.nom} (${cle}) : Spécial (dynamique)`);
  }
}
console.log(`TOTAL CARTES NORMALES : ${totalMots}`);

// Écriture dans data/themes.json
const cibleData = path.join(__dirname, '..', 'data', 'themes.json');
fs.writeFileSync(cibleData, JSON.stringify(THEMES, null, 2), 'utf8');
console.log('Écrit avec succès dans :', cibleData);

// Synchronisation avec dist/data/themes.json si présent
const cibleDist = path.join(__dirname, '..', 'dist', 'data', 'themes.json');
if (fs.existsSync(path.dirname(cibleDist))) {
  fs.writeFileSync(cibleDist, JSON.stringify(THEMES, null, 2), 'utf8');
  console.log('Synchronisé dans dist/data/themes.json');
}

// Synchronisation avec dist-portable/data/themes.json si présent
const ciblePortable = path.join(__dirname, '..', 'dist-portable', 'data', 'themes.json');
if (fs.existsSync(path.dirname(ciblePortable))) {
  fs.writeFileSync(ciblePortable, JSON.stringify(THEMES, null, 2), 'utf8');
  console.log('Synchronisé dans dist-portable/data/themes.json');
}
